:hivemq-link: https://www.hivemq.com
:hivemq-datahub-module-docs: {hivemq-link}/docs/hivemq/latest/data-hub/modules.html#hivemq-modules-for-data-hub
:hivemq-datahub-policy-docs: {hivemq-link}/docs/hivemq/latest/data-hub/policies.html
:hivemq-community: {hivemq-link}/community/

= HiveMQ 'Hello World' DataHub Module Example

image:https://img.shields.io/github/v/release/hivemq/hivemq-hello-world-datahub-module?style=for-the-badge[GitHub release (latest by date),link=https://github.com/hivemq/hivemq-hello-world-datahub-module/releases/latest]
image:https://img.shields.io/github/license/hivemq/hivemq-hello-world-datahub-module?style=for-the-badge&color=brightgreen[GitHub,link=LICENSE]

== Purpose
This repository contains a simple 'Hello World' example of a custom {hivemq-datahub-module-docs}[DataHub Module]
, intended for use with the {hivemq-link}[HiveMQ MQTT Broker].

This example is intended to show the files and metadata required to create a custom working module, as well as demonstrate how to implement some simple working Data Hub functionality using a custom module.  
This repo is also intended to be cloned and adapted for your own custom module needs, and to function as a basic starter template.

== Structure of the Custom Module

Custom modules must consist of a folder with the following files:

- `index.json`: This file contains the metadata for the custom module. It includes details that will be shown in the Control Center, such as the name of the module, a short description, and the version of the module.  It can also be used to set the the minimum HiveMQ Broker version required to use the custom module. It must also list the contents of the custom module.
- At least one {hivemq-datahub-policy-docs}[policy], referenced in the  `index.json` file. This can be either a data or behavioural policy. In this example, we show a simple data policy which validates if the incoming message is JSON and runs a short script to include a timestamp if this is the case.
- All schemas and scripts referenced in the policy. 

== Import into the Broker

To import the custom module into your Broker, first zip the folder, including the files. This zip file can then be uploaded via Data Hub within the Control Center.

== Support

Full documentation for Custom Modules can {hivemq-datahub-module-docs}[be found here].
For help or support in building your own custom modules, join {hivemq-community}[our community].

== License

HiveMQ Kafka Extension Hello World Customization is licensed under the `APACHE LICENSE, VERSION 2.0`.
A copy of the license can be found link:LICENSE[here].